apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: runtime-daemon
  namespace: runtime-copilot
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: runtime-daemon
      app.kubernetes.io/instance: runtime-daemon
      app.kubernetes.io/component: manager
      app.kubernetes.io/created-by: runtime-copilot
      app.kubernetes.io/part-of: runtime-copilot
      app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runtime-daemon
        app.kubernetes.io/instance: runtime-daemon
        app.kubernetes.io/component: manager
        app.kubernetes.io/created-by: runtime-copilot
        app.kubernetes.io/part-of: runtime-copilot
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: runtime-daemon
          image: ghcr.io/copilot-io/runtime-copilot/daemon:latest
          imagePullPolicy: IfNotPresent
          command:
            - /daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd-path
      volumes:
        - name: containerd-path
          hostPath:
              path: /etc/containerd
              type: DirectoryOrCreate
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10