# permissions for end users to edit registryconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: registryconfigs-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runtime-copilot
    app.kubernetes.io/part-of: runtime-copilot
    app.kubernetes.io/managed-by: kustomize
  name: registryconfigs-editor-role
rules:
- apiGroups:
  - config.registry.runtime.copilot.io
  resources:
  - registryconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.registry.runtime.copilot.io
  resources:
  - registryconfigs/status
  verbs:
  - get
