apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "charts.fullname" . }}-daemon
  namespace: {{ .Release.Namespace | default "default"}}
  labels:
      {{- include "charts.labels.daemon" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "charts.selectorLabels.daemon" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "charts.selectorLabels.daemon" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "charts.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.daemonPodSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-daemon
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.daemon_repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /daemon
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/containerd
              name: containerd-path
      volumes:
        - name: containerd-path
          hostPath:
            path: /etc/containerd
            type: DirectoryOrCreate
      terminationGracePeriodSeconds: 10