//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeHostConfigsSpec) DeepCopyInto(out *NodeHostConfigsSpec) {
	*out = *in
	if in.HostConfigs != nil {
		in, out := &in.HostConfigs, &out.HostConfigs
		*out = make([]NodeRegistryHostConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeHostConfigsSpec.
func (in *NodeHostConfigsSpec) DeepCopy() *NodeHostConfigsSpec {
	if in == nil {
		return nil
	}
	out := new(NodeHostConfigsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryConfigs) DeepCopyInto(out *NodeRegistryConfigs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryConfigs.
func (in *NodeRegistryConfigs) DeepCopy() *NodeRegistryConfigs {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRegistryConfigs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryConfigsList) DeepCopyInto(out *NodeRegistryConfigsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeRegistryConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryConfigsList.
func (in *NodeRegistryConfigsList) DeepCopy() *NodeRegistryConfigsList {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryConfigsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeRegistryConfigsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryConfigsSpec) DeepCopyInto(out *NodeRegistryConfigsSpec) {
	*out = *in
	if in.HostConfigs != nil {
		in, out := &in.HostConfigs, &out.HostConfigs
		*out = make([]NodeRegistryHostConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryConfigsSpec.
func (in *NodeRegistryConfigsSpec) DeepCopy() *NodeRegistryConfigsSpec {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryConfigsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryConfigsStatus) DeepCopyInto(out *NodeRegistryConfigsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryConfigsStatus.
func (in *NodeRegistryConfigsStatus) DeepCopy() *NodeRegistryConfigsStatus {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryConfigsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeRegistryHostConfig) DeepCopyInto(out *NodeRegistryHostConfig) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]CapabilitieType, len(*in))
		copy(*out, *in)
	}
	if in.SkipVerify != nil {
		in, out := &in.SkipVerify, &out.SkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeRegistryHostConfig.
func (in *NodeRegistryHostConfig) DeepCopy() *NodeRegistryHostConfig {
	if in == nil {
		return nil
	}
	out := new(NodeRegistryHostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfigs) DeepCopyInto(out *RegistryConfigs) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfigs.
func (in *RegistryConfigs) DeepCopy() *RegistryConfigs {
	if in == nil {
		return nil
	}
	out := new(RegistryConfigs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryConfigs) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfigsList) DeepCopyInto(out *RegistryConfigsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RegistryConfigs, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfigsList.
func (in *RegistryConfigsList) DeepCopy() *RegistryConfigsList {
	if in == nil {
		return nil
	}
	out := new(RegistryConfigsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RegistryConfigsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfigsSpec) DeepCopyInto(out *RegistryConfigsSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfigsSpec.
func (in *RegistryConfigsSpec) DeepCopy() *RegistryConfigsSpec {
	if in == nil {
		return nil
	}
	out := new(RegistryConfigsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfigsStatus) DeepCopyInto(out *RegistryConfigsStatus) {
	*out = *in
	if in.TotalNodes != nil {
		in, out := &in.TotalNodes, &out.TotalNodes
		*out = make([]RuntimeNum, len(*in))
		copy(*out, *in)
	}
	if in.SuccessNodes != nil {
		in, out := &in.SuccessNodes, &out.SuccessNodes
		*out = make([]RuntimeNum, len(*in))
		copy(*out, *in)
	}
	if in.FailedNodes != nil {
		in, out := &in.FailedNodes, &out.FailedNodes
		*out = make([]RuntimeNum, len(*in))
		copy(*out, *in)
	}
	if in.RunningNodes != nil {
		in, out := &in.RunningNodes, &out.RunningNodes
		*out = make([]RuntimeNum, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfigsStatus.
func (in *RegistryConfigsStatus) DeepCopy() *RegistryConfigsStatus {
	if in == nil {
		return nil
	}
	out := new(RegistryConfigsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfigsTemplate) DeepCopyInto(out *RegistryConfigsTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfigsTemplate.
func (in *RegistryConfigsTemplate) DeepCopy() *RegistryConfigsTemplate {
	if in == nil {
		return nil
	}
	out := new(RegistryConfigsTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeNum) DeepCopyInto(out *RuntimeNum) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeNum.
func (in *RuntimeNum) DeepCopy() *RuntimeNum {
	if in == nil {
		return nil
	}
	out := new(RuntimeNum)
	in.DeepCopyInto(out)
	return out
}
