name: Sync helm
on:
  push:
    tags:
      - v*
    branches:
      - main
jobs:
  chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
      - name: push chart
        env:
          ON_PLUGINS: true
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          make helm-sync